##!/usr/bin/python3
"""
  Author:  ZhengPeng.Han
  Purpose: Generate random data set.
  Created: 28/5/2020
"""
import random
import string

def dataSampling(func):
    def wrapper(datatype, datarange, num,*args, strlen=8):
        '''
            :Description: Generate a given condition random data set as a modifier.
            :param datatype: The type of data which include int float and string
            :param datarange: iterable data set
            :param num: Input parameters that means The final result of the number of elements
            :param strlen:The length of input strings
            :param args: A variable length parameter that be used in dataSampling and dataScreening
            :return: a function that be used in dataScreening
        '''
        result = set()
        if (datatype is int):
            while len(result) < num:
                it = iter(datarange)
                item = random.randint(next(it), next(it))
                result.add(item)
        elif (datatype is str):
            while len(result) < num:
                item = ''.join(random.SystemRandom().choice(datarange) for _ in range(strlen))
                result.add(item)
        elif (datatype is float):
            while len(result) < num:
                it = iter(datarange)
                item = random.uniform(next(it), next(it))
                result.add(item)
        return func(result, *args)
    return wrapper

@dataSampling
def dataScreening(data,*args):
    '''
        :param data:The data used for filtering which generated by dataSampling
        :param args: A variable length parameter that be used in dataSampling and dataScreenin
        :return: a dataset
    '''
    scrresult = set()
    for it in data:
        if (type(it) is int):
            cond = iter(args)
            if (next(cond) <= it and next(cond) >= it):
                scrresult.add(it)
        elif (type(it) is str):
            for condstr in args:
                if (condstr in it):
                    scrresult.add(it)
        elif (type(it) is float):
            cond = iter(args)
            if (next(cond) <= it and next(cond) >= it):
                scrresult.add(it)
    print(scrresult)

dataScreening(str, string.ascii_letters + string.digits + "@#$!", 5,'a')
dataScreening(int,(0,100),5,10,90)
dataScreening(float,(0,100),5,10,90)

